name: Deploy to itch.io

on:
  release:
    types:
      - released

jobs:
  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: temurin

      - name: Build
        run: ./gradlew html:dist

      - name: Set up butler
        uses: jdno/setup-butler@v1

      - name: Publish game to itch.io
        run: |
          butler push html/build/dist pepek42/rain-libgdx:html --userversion ${{ github.ref_name }}
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
